config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/GCore:
      branch: master
      repo: https://github.com/grycap/GCore
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/GCore git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-myrtle-skunk.sh
        container: qc.acc_beady-chocolate-tortoise
  QC.Doc:
    repos:
      github.com/grycap/GCore find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-flax-frog.sh
        container: qc.doc_shaky-charcoal-mammoth
      github.com/grycap/GCore git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lilac-dragonfly.sh
        container: qc.doc_thirsty-purple-shrimp
      github.com/grycap/GCore markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-zucchini-angora.sh
        container: qc.doc_lovely-black-flounder
  QC.Lic:
    repos:
      github.com/grycap/GCore licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-sepia-havanese.sh
        container: qc.lic_lanky-amethyst-coral
  QC.Sty:
    repos:
      github.com/grycap/GCore jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-seashell-chameleon.sh
        container: qc.sty_randy-fuchsia-chicken
      github.com/grycap/GCore stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-jade-lizard.sh
        container: qc.sty_blurry-yellow-alligator
  QC.Ver:
    repos:
      github.com/grycap/GCore get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-peach-lynx.sh
        container: qc.ver_woolly-malachite-foxhound
timeout: 1800
