config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/GCore:
      branch: master
      repo: https://github.com/grycap/GCore
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/GCore git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-corn-dane.sh
        container: qc.acc_shabby-orange-ostrich
  QC.Doc:
    repos:
      github.com/grycap/GCore find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-myrtle-caiman.sh
        container: qc.doc_lanky-olive-fowl
      github.com/grycap/GCore git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-lilac-saola.sh
        container: qc.doc_hilly-harlequin-uguisu
      github.com/grycap/GCore markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-red-worm.sh
        container: qc.doc_breezy-olivine-chicken
  QC.Lic:
    repos:
      github.com/grycap/GCore licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-smalt-kakapo.sh
        container: qc.lic_hilly-mauve-boar
  QC.Met:
    repos:
      github.com/grycap/GCore cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-celadon-discus.sh
        container: qc.met_shabby-charcoal-civet
      github.com/grycap/GCore validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-lilac-badger.sh
        container: qc.met_snappy-linen-dragonfly
  QC.Sty:
    repos:
      github.com/grycap/GCore jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-malachite-turtle.sh
        container: qc.sty_gimpy-silver-liger
      github.com/grycap/GCore stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cardinal-quetzal.sh
        container: qc.sty_pokey-alizarin-moose
  QC.Ver:
    repos:
      github.com/grycap/GCore get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-mauve-wolverine.sh
        container: qc.ver_tacky-pumpkin-lobster
timeout: 1800
